[dotenv@17.2.3] injecting env (19) from .env -- tip: 🛠️  run anywhere with `dotenvx run -- yourcommand`
Connecting DB...
Setting AutoReply to disabled for 17841478194355579...
To properly test webhook execution without signing, I'll bypass the signature locally just for this test
